services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: worldcup_pred
      POSTGRES_USER: worldcup_user
      POSTGRES_PASSWORD: worldcup_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
